{% set name = "sqlalchemy-spanner" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # source from PyPI is missing version.py
  url: https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy/archive/refs/tags/v{{ version }}.zip
  sha256: 858e8a552fb9d753347ccdb599e5b9ea8667b51b578b9eb4a6aee64bba1c5de4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - sqlalchemy >=1.1.13
    - google-cloud-spanner >=3.12.0
    - alembic

test:
  imports:
    - sqlalchemy_spanner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy
  summary: SQLAlchemy dialect integrated into Cloud Spanner database
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - hadim
